name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.26.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Cloner
        uses: actions/checkout@v7

      - name: Installer
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Builder
        run: go build .

      - name: Tester
        run: go test -v -cover ./...

      - name: Linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest