name: CI
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Cloner
      uses: actions/checkout@v3

    - name: Installer
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Builder
      run: go build .

    - name: Tester
      run: go test -v -cover ./...

    - name: Linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest